import { defaultTypeMap } from "./lib/constants.js";

export interface PrismaGuardOptions {
  /**
   * Output directory for the generated field mapping
   * @default "./node_modules/.prisma-guard"
   */
  outputDir?: string;
  /**
   * Whether to log stripped fields to the console
   * @default false
   */
  debug?: boolean;
}

export interface ModelFields {
  scalar: string[];
  relations: { name: string; model: string }[];
}

export type GeneratorOptions = {
  schemaDir: string;
  outputDir: string;
  dryRun?: boolean;
};

export type ZodGeneratorOptions = {
  schemaDir: string;
  outputDir: string;
  omitIds?: boolean;
  omitDates?: boolean;
  dryRun?: boolean;
  typeMap?: Record<string, string>;
  decorators?: Record<string, string>;
  zodOmit?: string[];
  autoTrim?: boolean;
  schemaSuffix?: string;
  enumSuffix?: string;
  useJsDoc?: boolean;
};

/**
 * Configuration options for Prisma Guard.
 *
 * @example
 * ```typescript
 * import { defineConfig } from "@explita/prisma-guard";
 *
 * export default defineConfig({
 *   schemaDir: "./prisma",
 *   outputDir: "./src/generated",
 *   omitIds: true,
 *   autoTrim: true,
 *   zodOmit: ["password", "resetToken"]
 * });
 * ```
 */
export type PrismaGuardConfig = {
  /**
   * Path to the directory containing your Prisma schema files.
   *
   * @default "./prisma"
   * @example "./prisma"
   * @example "./src/db/schema"
   */
  schemaDir?: string;

  /**
   * Output directory for generated files (Zod schemas, guards, and lib).
   *
   * - If set to a committed directory (e.g., `./src/generated`), Zod schemas will be available in your code.
   * - If not set, files are written to `node_modules/.prisma-guard` (suitable for runtime guard only).
   *
   * @default "node_modules/.prisma-guard"
   * @example "./src/generated"
   * @example "./generated"
   */
  outputDir?: string;

  /**
   * Remove all `@id` fields from generated Zod schemas.
   *
   * Useful when IDs are auto-generated by the database and should not be validated.
   *
   * @default false
   * @example true
   */
  omitIds?: boolean;

  /**
   * Remove timestamp fields (typically `createdAt` and `updatedAt`) from generated Zod schemas.
   *
   * These fields are usually set by the database and don't need validation.
   *
   * @default false
   * @example true
   */
  omitDates?: boolean;

  /**
   * Whether to generate Zod schemas for your Prisma models.
   *
   * If `false`, only the runtime guard utilities are generated.
   *
   * @default true
   * @example true
   */
  generateZod?: boolean;

  /**
   * Global list of field names to omit from ALL generated Zod schemas.
   *
   * Use `/// @zod.include` in your schema to override omission for specific fields.
   *
   * @default []
   * @example ["password", "resetToken", "secret"]
   */
  zodOmit?: string[];

  /**
   * Automatically add `.trim()` to all `z.string()` validations.
   *
   * Prevents whitespace-only strings from passing validation.
   *
   * @default true
   * @example true
   */
  autoTrim?: boolean;

  /**
   * Suffix appended to generated Zod schema names.
   *
   * @default "Schema"
   * @example "Schema"  // UserSchema
   * @example "Validator"  // UserValidator
   */
  schemaSuffix?: string;

  /**
   * Suffix appended to generated Zod enum schemas.
   *
   * @default "Enum"
   * @example "Enum"  // RoleEnum
   * @example "Values"  // RoleValues
   */
  enumSuffix?: string;

  /**
   * Use JSDoc comments in generated TypeScript files.
   *
   * When enabled, generated schemas include JSDoc annotations for better IDE support.
   *
   * @default false
   * @example true
   */
  useJsDoc?: boolean;

  /**
   * Enable debug logging to console.
   *
   * Useful for troubleshooting generation issues or understanding the sanitization process.
   *
   * @default false
   * @example true
   */
  debug?: boolean;

  /**
   * Automatically format generated files with Prettier.
   *
   * Uses your project's Prettier configuration if available.
   *
   * @default true
   * @example true
   */
  prettier?: boolean;

  /**
   * Prevent automatic updates to `.gitignore`.
   *
   * By default, Prisma Guard adds generated folders to `.gitignore`.
   * Set to `true` if you want to manage this manually.
   *
   * @default false
   * @example true
   */
  skipGitignore?: boolean;

  /**
   * Override default Prisma-to-Zod type mappings.
   *
   * Only specify the types you want to override. Supports any Zod chain.
   *
   * @example
   * ```typescript
   * typeMap: {
   *   DateTime: "z.string().datetime()",
   *   Decimal: "z.string().regex(/^\\d+\\.\\d{2}$/)",
   *   Json: "z.record(z.unknown())"
   * }
   * ```
   */
  typeMap?: {
    [K in keyof typeof defaultTypeMap]?: string;
  } & {
    /**
     * Custom mapping for any Prisma type or field name.
     *
     * @example
     * ```typescript
     * typeMap: {
     *   // Override specific field names
     *   "User.email": "z.string().email().toLowerCase()",
     *   // Override custom scalar types
     *   "UUID": "z.string().uuid()"
     * }
     * ```
     */
    [k: string]: string;
  };

  /**
   * Named validation decorators for reuse across your Prisma schema.
   *
   * Define once in config, use everywhere with `/// @zod.use(name)`.
   *
   * @example
   * ```typescript
   * import { pg, z } from "@explita/prisma-guard";
   *
   * decorators: {
   *   email: pg.email().trim().toLowerCase(),
   *   password: z.string().min(8).regex(/[A-Z]/),
   *   futureDate: pg.refine(date => date > new Date())
   * }
   * ```
   */
  decorators?: Record<string, string>;
};
